### ISSUE TITLE
Improve the CNN model

### ISSUE THREAD

**Issue by jyotirmoy-paul** [jyotirmoy-paul/DoodleMe#1]
# Improve the CNN model
* The model in use is trained with 0.605 million unique doodles for 20 epochs
* And tested against 0.132 million unique doodles
* Obtained max accuracy of 68.29% on the test dataset
> The details of the CNN Architecture can be found [here](https://github.com/jyotirmoy-paul/DoodleMe/blob/master/cnn_model_v6_28_123.ipynb)
* <b>Find the Google's original dataset [here](https://github.com/googlecreativelab/quickdraw-dataset)<b> (Numpy bitmaps)
* <b>Find my modified dataset [here](https://github.com/robo-nic/dataset)<b>

## It would be great if you could improve the accuracy of the model, also if you could add new doodles into the already existing model

**Comment by jalotra** [comment]
@jyotirmoy-paul Do you want us to increase the depth of the cnn ? Or use the same spatial dimensions and just to tweak the parameters?

**Comment by jyotirmoy-paul** [comment]
@jalotra I did try tweaking the parameters to a certain extent, but with no improvements. I was wondering if changing the architecture could help, I mean adding new convolutional layers with different amount of filters and varying kernel sizes, or might be changing the number of units in the hidden layers. But was always worried, doing too much might be an overkill.

**Comment by jalotra** [comment]
@jyotirmoy-paul What about transfer learning ?

**Comment by jyotirmoy-paul** [comment]
@jalotra Well as a begineer in Deep Learning, I'm not much familiar with `transfer learning`. But if you can suggest a way to use `transfer learning` for the doodle recognition, I'm more than willing to learn it.

**Comment by jalotra** [comment]
@jyotirmoy-paul  As far as I can search the net, Kaggle held a competition around this dataset.. Check this https://www.kaggle.com/c/quickdraw-doodle-recognition/leaderboard. So a score of around 95 is achievable using transfer learning and deep ensemble. One of the competitors has also written a blog on this : https://towardsdatascience.com/doodling-with-deep-learning-1b0e11b858aa. What do you say?

**Comment by jyotirmoy-paul** [comment]
@jalotra Quite interesting, thanks for sharing the links. 
What I observed is using CNN is not going to give a very high performing model.
Also I wish to tell something, I trained the model on grayscale 28x28 images (motivated by the MNIST dataset), so my model was looking at the picture as a whole, I'm not making use of the strokes information. So what if we can use transfer learning and make use of the strokes information? I believe that way a powerful model can be built.

**Comment by jalotra** [comment]
@jyotirmoy-paul Yup, that's true because shrinking the image causes loss of spatial information like gradients in different directions. Well as far as training a new cnn using transfer learningis considered I will have to study which base model to pick up. In the meantime I am thinking of creating a separate slack room for this issue. If you can create a slack room send a link to me as well. Because discussing everything here will be an overkill.

**Comment by jyotirmoy-paul** [comment]
@jalotra I did create a channel on Slack, but tell me how am i suppose to invite you there?

**Comment by jalotra** [comment]
@jyotirmoy-paul Send the invite link to shivam_11710495@nitkkr.ac.in

**Comment by jyotirmoy-paul** [comment]
@jalotra I sent you the invitation link, please do check it

**Comment by jalotra** [comment]
> @jalotra I sent you the invitation link, please do check it

Okay, I am in.
